### ISSUE TITLE
Menu text disappears on mouse over

### ISSUE THREAD

**Issue by jose1711** [cflavio/yorg#36]
In current `master` if I mouse over a menu item the text disappears. Arch Linux, 64bit, nvidia gpu with binary driver, `yorg` installed using AUR (https://aur.archlinux.org/packages/yorg-git/). Gameplay is okay.

![obrázok](https://user-images.githubusercontent.com/1406222/103142500-55cef580-4704-11eb-89a7-9a33f970d632.png)

**Comment by cflavio** [comment]
Hi! Thank you very much for reporting this! It seems that it happens only with Nvidia drivers, since I don't observe it on systems with Intel or AMD drivers. Unfortunately, I don't have a computer with Nvidia GPU, so I can't replicate the issue (the GLSL code should be pretty correct since it is correctly processed by other drivers, so I should look at some specific workaround for your scenario). If I will get a computer with Nvidia GPU I will definitely look at this issue, thanks!

**Comment by jose1711** [comment]
Thank you, if it helps the GPU is 750Ti and the driver version is: `455.45.01`.

**Comment by jose1711** [comment]
The problem vanished after updating Panda3D to version 1.10.8. Looks like Nvidia is not to blame here.
